name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Install selenium
        run: pip install selenium
      - name: Test
        run: cargo test --verbose --features integration-test
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Audit
        run: cargo audit
